### ISSUE TITLE
FR: Undo/Redo

### ISSUE THREAD

**Issue by anonimitoraf** [DanielDe/org-web#131]
Hi! Thanks for this package!

Any plans for undo/redo-ing changes?

Also, follow-up question: Is there a way to auto-cleanup bak files?

**Comment by DanielDe** [comment]
> Any plans for undo/redo-ing changes?

Nothing at the moment, but its a good idea!

> Also, follow-up question: Is there a way to auto-cleanup bak files?

No, there's no option for that right now. They're there just in case org-web does something unexpected (though I'm not sure that's ever happened, so perhaps its time to consider an option to disable these!)
