### ISSUE TITLE
FLAC playback hang on version 3.5.3, Galaxy S22

### ISSUE THREAD

**Issue by JohnConner** [DanielDe/org-web#137]
I bought a Galaxy S22 ultra, and migrated my data to the phone. After updating all software to the latest version (with VLC at 3.5.3), I found that a flac file would stop playing at the 23 second mark (Joe Satriani, Flying in a Blue Dream). I thought that maybe the file had been corrupted in the migration, so I deleted the album and recopied it from my desktop. Still halted at the 23 second mark. I installed another audio player, and the file was able to play. I deinstalled and reinstalled (from the PlayStore) version 3.5.3, still same issue. I deleted the cache, still same issue. My old phone had 3.5.2, and was able to play the song with no trouble, so I deinstalled VLC on my new phone, and downloaded and installed the APK for version 3.5.2 on my new phone, and the song plays without error. It appears to be a problem decoding the file.

**Comment by DanielDe** [comment]
Hi @JohnConner, I'm wondering if maybe you accidentally posted this on the wrong repo? I'm not sure what this could have to do with org-web, but let me know if I'm wrong!

**Comment by JohnConner** [comment]
ahhhh crap, you're right, my bad

**Comment by DanielDe** [comment]
No worries :)

**Comment by JohnConner** [comment]
posted in wrong repo :/
