### ISSUE TITLE
Add support for keybindings

### ISSUE THREAD

**Issue by dustinlacewell** [DanielDe/org-web#23]
Navigation, editing, and so on. Currently very mouse oriented.

**Comment by dustinlacewell** [comment]
Well that's one.

Another is using org as a format for collaboration with people who are not emacs users. I am looking to establish a community knowledge-base and would love to use org-mode. If people could start by using this web-interface we'll get a lot more action. Also, this can be a great way to expose people to org-mode. I totally support your mobile focus, but with some keybindings, this easily becomes useful on the desktop too.

Great work.

**Comment by DanielDe** [comment]
> If people could start by using this web-interface we'll get a lot more action. Also, this can be a great way to expose people to org-mode.

Ah, yeah, I really like that! I'm convinced :) 

I'll be picking up development on org-web again shortly. I'll see if I can get around to this soon!

**Comment by DanielDe** [comment]
Hey @dustinlacewell, I just merged keybinding support into `master` and pushed the changes live. There are still some glaring bugs in trying to set custom bindings, but its a lot more usable with a keyboard already. 

Let me know what you think!
