### ISSUE TITLE
Actions not working on Firefox 62.0.3 on Windows

### ISSUE THREAD

**Issue by neomodern** [DanielDe/org-web#29]
Bugs first reported here #28 - the top 5 buttons don't work, but Deadline and Scheduled do ![](https://i.imgur.com/Ol1eP5f.png)

**Comment by DanielDe** [comment]
Ah, thanks so much for reporting this! Judging by the look of the header bar in your screenshot, there's a whole lot that's messed up in FF on Windows! I'll check it out!

**Comment by DanielDe** [comment]
Ah, good news: I can reproduce this in FF on my Mac, too! That'll make it a whole lot easier to fix.

**Comment by DanielDe** [comment]
This is fixed now! Thanks again for the report!
