### ISSUE TITLE
Bug Report - error message when adding an entry.

### ISSUE THREAD

**Issue by Babawaba** [DanielDe/org-web#30]
Adding an entry results in the following error message "Uh oh, you ran into a bug!

This was probably the result of an error in attempting to parse your org file. It'd be super helpful if you could create an issue (and include the org file if possible!)"

I tried it on several org files and the results are the same. It was working fine yesterday. Attached is a test file I used to recreate the error message.
[Test.txt](https://github.com/DanielDe/org-web/files/2466721/Test.txt)

I love concept, by the way. I've been looking for something like this for a long time. Well done!

**Comment by DanielDe** [comment]
Hey, thanks so much for the report and the file to repro! I'll check this out ASAP and get back to you here

**Comment by DanielDe** [comment]
This is fixed now, thanks again for the report!
