### ISSUE TITLE
Integrate rclone as a storage provider

### ISSUE THREAD

**Issue by dinkonin** [DanielDe/org-web#35]
If it's possible. It will be awesome to have all the backends supported by [rclone](https://rclone.org/).

**Comment by DanielDe** [comment]
Ah, that would be nice, but it looks like rclone is a command line utility. org-web operates entirely client side in a web browser.

**Comment by dinkonin** [comment]
Im not sure it helps but Rclone supports http server mode, shown [here.](https://rclone.org/rc/).

**Comment by DanielDe** [comment]
Oh that’s pretty neat! I still don’t currently have any near term plans to run my own backend, but this makes the thought more enticing.
