### ISSUE TITLE
Bad UTF-8 encoding

### ISSUE THREAD

**Issue by todoniko** [DanielDe/org-web#37]
Cyrillic in org file(s) is not shown properly.
Attaching sample file.
[test.org.txt](https://github.com/DanielDe/org-web/files/2931737/test.org.txt)

**Comment by todoniko** [comment]
Had some free time on my hands.
So far the issue is present for Google Drive only. Tests with the same file for dropbox were fine.
Modifying the response in https://github.com/DanielDe/org-web/blob/55a410f8098a2647b378d084a78e54ba564fa31d/src/sync_backend_clients/google_drive_sync_backend_client.js#L283
to
`resolve(decodeURIComponent(escape(response.body)))`
Fixes the issue.

**Comment by DanielDe** [comment]
Wow, that's awesome, thanks so much! I'm happy to accept a PR if you'd like to submit one, @todoniko, or I can implement this myself!

**Comment by todoniko** [comment]
I haven't tested this very thoroughly, just quick fix. 
Please do implement the fix if it is not causing any trouble.

**Comment by DanielDe** [comment]
I just pushed [this fix](https://github.com/DanielDe/org-web/commit/1602a702a388cc49de15b52d3ce699a70272816a) live! Thanks again for your help @todoniko
