### ISSUE TITLE
Bug: The parser removes in-buffer settings

### ISSUE THREAD

**Issue by munen** [DanielDe/org-web#55]
Bug: When making changes to an existing org file, after synchronizing it [in-buffer settings](https://orgmode.org/manual/In_002dbuffer-settings.html) are lost.
Expectation: The org-web parser leaves in-buffer settings in place. 

Steps to reproduce:

- In Emacs, create an org-file with in-buffer settings
- Open it in org-web
- Make any kind of change which triggers a sync from org-web

Here's a screenshot of Magit showing the diff after these steps:

![image](https://user-images.githubusercontent.com/505721/62306606-73058300-b482-11e9-8697-b18285caacb5.png)

**Comment by DanielDe** [comment]
Ah, yes indeed. Thanks so much for the issue!
