### ISSUE TITLE
Bug: The parser breaks indentation of existing lists

### ISSUE THREAD

**Issue by munen** [DanielDe/org-web#56]
Bug: The org-web parser re-indents existing lists which can cause a change in semantics.
Expectation: The org-web parser doesn't re-indent existing lists. Alternative: The org-web parser re-indents the whole list.

Steps to reproduce:

- Create an existing org-file which a header and within this header a list which is indented (doesn't start at the beginning of the line)
- Open the file in org-web, make any change that triggers a synchronization

Example:

```
** GTD
*** Structure
**** things.org
 - Inbox
 - Next
   - TODO 1
   - TODO 2
   - Area of Interest 1
     - TODO 1
```

Here's a screenshot showing the re-indentation after synchronizing with org-web. Note that this is a semantic change to the list. 

![image](https://user-images.githubusercontent.com/505721/62307219-8107d380-b483-11e9-9e32-ee0e2c958b66.png)

**Comment by DanielDe** [comment]
Another nice find, thanks @munen :)

**Comment by munen** [comment]
@DanielDe You're very welcome^^ Thank you very much for this great project! I'm a heavy Emacs (and org) user and currently use Beorg on iOS to have a complete GTD workflow. Beorg is nice, however, it's neither OSS nor cross-platform, so I was stoked when I read about org-web!

I would have preferred to send a PR instead of this report, and actually dug into the parsing code for a bit. I couldn't get it to work in my current spare time, so I wanted to share the issue.

However, generally speaking, I'd be happy if I can contribute a little something to this great project at some point. Thanks, again :pray:

**Comment by munen** [comment]
@DanielDe I did look a little more around in the parser. It's trivial to find where the error happens, but it's not trivial to fix without understanding your idea of the domain model of the internal representation of the org file. It's also nice to test locally (manually) thanks to you having set up the ability to use Dropbox sync on localhost.

But it's actually a great place to get started to understand org-web better and set myself up for potential future contributions. For this reason, I'd like to make myself available for a pairing session with screen sharing. The suggested targets are:

- Short discussion of the internal org representation
- Have a spike with you on fixing this issue together
- Writing some documentation for future developers

That is if you do have the time for onboarding a random stranger from the Internet^^

**Comment by munen** [comment]
Update: As a quick-fix, I was going to adapt my org files to the syntax that's seemingly preferred by org-web (meaning every list should start without indentation). However, whilst going through that process, I realized that org-web likes to always(?) position the first element after a headline without indentation. I could live with lists starting on the first line, but having consistency in a text-file is also nice.

Hence I didn't finish my quick-fix. I'll have to tackle this bug first before I can really become a user (which I'm very much looking forward to!^^).

Example: 
![image](https://user-images.githubusercontent.com/505721/62415156-7127f500-b625-11e9-9161-1dc5d79fdb32.png)

**Comment by munen** [comment]
This issue is solved by PR https://github.com/DanielDe/org-web/pull/60.
