### ISSUE TITLE
Request to discuss steering of org-web

### ISSUE THREAD

**Issue by munen** [DanielDe/org-web#72]
Let me start by saying that I'm extraordinarily grateful to you, DanielDe, for creating and nurturing org-web to this point! I'm using Emacs for most of my work and Org mode for everything from note taking, time tracking, invoicing, slides, bookkeeping and so forth. Therefore, having a solid tool to promote working on Org mode files on the go is very valuable to me. The same goes for a simple tool that non-Emacs users can use to have simple access to the same data. You've been the first to tackle this in a sustainable way - with a good technology stack, good code quality and with an open source license. Your work is immensely helpful to a great many people!

Having said that, I'm a little confused by [you rejecting a pull request](https://github.com/DanielDe/org-web/pull/67) without discussion which makes org-web usable for non-macOS users by default (that is mostly Linux and Windows users). I'm personally invested in getting org-web bug-free. I use it daily, I'm doing marketing for it online and offline and I am currently onboarding other people who are equally Emacs users and non Emacs users. In fact, I'm even onboarding people that have previously used Macs who now pivot to Linux. So this particular PR is of great value to those people. 

If you're planning to target only macOS for org-web (which imo is a generic web-app), I'm afraid that I will have to make a fork which would be unfortunate since I feel that org-web is just about to get some great traction. Since breaking this small community up is definitively not my intention, I'd rather start with a dialogue first.

At this moment in time, you're the only person deciding how this project evolves. That is definitively you're prerogative as you've put in _all_ the work in the beginning and made org-web accessible to us. 

However, I wonder how you plan to go forward in the longer term. As I see it, there's more contributors coming along at this point. It also seems that you're short on time to work on org-web. Looking at these two things together, my questions are:

- Would you be willing to transfer this project to a Github organization? This would have the benefit that the project can potentially evolve independently of a single person and more people could get involved in a more integrated manner. 
  - NB: Moving would keep all stars, PRs, issues and create a redirect for existing users.
- If so, could you formulate criteria based on which you'd accept contributors who have merge write rights and get a say in the steering of this project?

I apologize if this request sounds rude to you in any way. It is definitively not my intent. The intent is to give input on what my perception is on how org-web can evolve in the most efficient way. However, I’m just stating an opinion. Whatever is your take, I’ll be happy for the community to have received this great gift from you which is org-web. Thank you! 🙏🏻

**Comment by DanielDe** [comment]
Hey @munen, I just reopened #67. My intention wasn't to cut off the discussion, so sorry about that! But I've left more thoughts specific to that PR there. 

I haven't thought much about longer term contributions, so I don't have many well formed opinions there. But I still view org-web as a pet project of mine, so I'm pretty strongly in favor of folks with different needs simply forking the project and implementing their changes there, instead of growing this repo into a larger organization. I made the project open source so that that kind of thing could happen easily (as well as so folks could inspect the source themselves to build trust that there's no funny business when dealing with their private files).

**Comment by munen** [comment]
@DanielDe Thank you very much for the quick and clear comment!

I really like your attitude and how you've fostered the project up until this point. It's also good that we had a quick chat on where you see this project going - I'm very grateful for your clear words regarding this topic. 

Personally, I'm very grateful for org-web! However, we do deviate in the vision of the project. Your focus is going to be on mobile. For me, it's a great win that it's also a web app that can be used from a desktop browser.

Therefore, I'll take you up on the offer of creating a fork. Also, this is in the best Emacs tradition, right?(; 

May both paths be the right path! Thank you for all, DanielDe! :pray: :bowing_man:
