### ISSUE TITLE
Remove Google Analytics

### ISSUE THREAD

**Issue by SamHasler** [DanielDe/org-web#75]
Could you please remove google analytics from the codebase:

https://github.com/DanielDe/org-web/blob/fc5f1d3b4e36724acdcd266c44071328fb9c6d0d/src/store.js#L3

I don't think I'd want to use this if it could be logging anything about how I'm using it to GA.

**Comment by DanielDe** [comment]
Hi @SamHasler. I didn't put it there accidentally as your phrasing seems to indicate :) I use Google Analytics for error tracking and to get some insight into what features folks are using so as to better focus effort. And note that I specifically redact file contents from the logging: https://github.com/DanielDe/org-web/blob/master/src/middleware/google_analytics_logging.js#L9

But I do understand your desire to not be tracked by GA, and you've got a couple options: 
1) Use an ad/tracking blocker on your platform of choice. They exist for most browsers, including on iOS and Android. I use uBlock Origin for Chrome on my Mac. 
2) Fork and host your own version of org-web with GA removed. org-web runs entirely on the frontend, so its really easy to deploy and host. And you can remove GA tracking by changing one line: https://github.com/DanielDe/org-web/blob/master/src/store.js#L14 (just remove `googleAnalyticsLogger` here). 

If you do go the route of hosting your own version of org-web I'd be more than happy to help you get that set up. I'm going to close this issue, but please feel free to continue commenting here (or reach out to me by email which you can find in the git log of this project).
